# Generated by Django 6.0.6 on 2026-07-12 10:15

import django.db.models.deletion
import provinces.managers.province_manager
import provinces.managers.region_manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('map_color', models.CharField(default='#2E7D32', help_text='HEX color code (#RRGGBB).', max_length=7, verbose_name='Map Color')),
                ('display_order', models.PositiveSmallIntegerField(db_index=True, default=1, verbose_name='Display Order')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='provinces_r_slug_eaf5db_idx'), models.Index(fields=['display_order'], name='provinces_r_display_bbe289_idx'), models.Index(fields=['is_active'], name='provinces_r_is_acti_82b411_idx')],
            },
            managers=[
                ('objects', provinces.managers.region_manager.RegionManager()),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_code', models.PositiveSmallIntegerField(db_index=True, unique=True, verbose_name='Plate Code')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('map_x', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Map X')),
                ('map_y', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Map Y')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='Featured')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provinces', to='provinces.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
                'ordering': ['plate_code'],
                'indexes': [models.Index(fields=['region'], name='provinces_p_region__fb0ed5_idx'), models.Index(fields=['slug'], name='provinces_p_slug_b58625_idx'), models.Index(fields=['plate_code'], name='provinces_p_plate_c_fc91aa_idx'), models.Index(fields=['is_active'], name='provinces_p_is_acti_885cc8_idx'), models.Index(fields=['is_featured'], name='provinces_p_is_feat_de610c_idx'), models.Index(fields=['region', 'is_active'], name='provinces_p_region__f66577_idx')],
            },
            managers=[
                ('objects', provinces.managers.province_manager.ProvinceManager()),
            ],
        ),
    ]
