# Generated by Django 6.0.6 on 2026-06-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='İl Adı')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL Uzantısı')),
                ('plate_code', models.PositiveSmallIntegerField(unique=True, verbose_name='Plaka Kodu')),
                ('region', models.CharField(choices=[('Marmara', 'Marmara Bölgesi'), ('Ege', 'Ege Bölgesi'), ('Akdeniz', 'Akdeniz Bölgesi'), ('İç Anadolu', 'İç Anadolu Bölgesi'), ('Karadeniz', 'Karadeniz Bölgesi'), ('Doğu Anadolu', 'Doğu Anadolu Bölgesi'), ('Güneydoğu Anadolu', 'Güneydoğu Anadolu Bölgesi')], max_length=20, verbose_name='Bölge')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Enlem')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Boylam')),
            ],
            options={
                'verbose_name': 'İl',
                'verbose_name_plural': 'İller',
                'ordering': ['plate_code'],
            },
        ),
    ]
