# Generated by Django 6.0.6 on 2026-07-09 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Bölge Adı')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('map_color', models.CharField(default='#2E7D32', help_text='HEX formatında renk kodu (#RRGGBB).', max_length=7, verbose_name='Harita Rengi')),
                ('display_order', models.PositiveSmallIntegerField(db_index=True, default=1, verbose_name='Gösterim Sırası')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Bölge',
                'verbose_name_plural': 'Bölgeler',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['display_order'], name='provinces_r_display_bbe289_idx'), models.Index(fields=['is_active'], name='provinces_r_is_acti_82b411_idx')],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_code', models.PositiveSmallIntegerField(db_index=True, unique=True, verbose_name='Plaka Kodu')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='İl Adı')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Enlem')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Boylam')),
                ('map_x', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Harita X')),
                ('map_y', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Harita Y')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provinces', to='provinces.region', verbose_name='Bölge')),
            ],
            options={
                'verbose_name': 'İl',
                'verbose_name_plural': 'İller',
                'ordering': ['plate_code'],
                'indexes': [models.Index(fields=['region'], name='provinces_p_region__fb0ed5_idx'), models.Index(fields=['slug'], name='provinces_p_slug_b58625_idx'), models.Index(fields=['plate_code'], name='provinces_p_plate_c_fc91aa_idx'), models.Index(fields=['is_active'], name='provinces_p_is_acti_885cc8_idx'), models.Index(fields=['region', 'is_active'], name='provinces_p_region__f66577_idx')],
            },
        ),
    ]
