# Generated by Django 6.0.6 on 2026-06-28 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provinces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Malzeme Adı')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL Uzantısı')),
            ],
            options={
                'verbose_name': 'Malzeme',
                'verbose_name_plural': 'Malzemeler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tarif Adı')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL Uzantısı')),
                ('description', models.TextField(verbose_name='Kısa Açıklama')),
                ('instructions', models.TextField(verbose_name='Yapılışı')),
                ('prep_time_minutes', models.PositiveSmallIntegerField(verbose_name='Hazırlama Süresi (Dk)')),
                ('cook_time_minutes', models.PositiveSmallIntegerField(verbose_name='Pişirme Süresi (Dk)')),
                ('serving_size', models.PositiveSmallIntegerField(verbose_name='Kaç Kişilik')),
                ('difficulty', models.CharField(choices=[('Kolay', 'Kolay'), ('Orta', 'Orta'), ('Zor', 'Zor')], max_length=10, verbose_name='Zorluk')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_published', models.BooleanField(default=True, verbose_name='Yayında mı?')),
                ('meta_title', models.CharField(blank=True, help_text='Boş bırakılırsa Tarif Adı kullanılır.', max_length=60, verbose_name='SEO Başlığı')),
                ('meta_description', models.CharField(blank=True, help_text='Boş bırakılırsa Kısa Açıklama kullanılır.', max_length=160, verbose_name='SEO Açıklaması')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='provinces.province', verbose_name='Ait Olduğu İl')),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tarifler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='recipes/%Y/%m/', verbose_name='Görsel')),
                ('alt_text', models.CharField(max_length=100, verbose_name='Alternatif Metin (SEO)')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Ana Görsel mi?')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıralama')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Tarif Görseli',
                'verbose_name_plural': 'Tarif Görselleri',
                'ordering': ['order', '-is_primary'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=50, verbose_name='Miktar')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Birim')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıralama')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_recipes', to='recipes.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Tarif Malzemesi',
                'verbose_name_plural': 'Tarif Malzemeleri',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['province', 'is_published'], name='recipes_rec_provinc_e11f8d_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['slug'], name='recipes_rec_slug_412256_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('recipe', 'ingredient')},
        ),
    ]
