# Generated by Django 6.0.6 on 2026-07-12 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provinces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='recipes_cat_slug_178eca_idx'), models.Index(fields=['is_active'], name='recipes_cat_is_acti_c66f7a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Cuisine',
                'verbose_name_plural': 'Cuisines',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='recipes_cui_slug_681697_idx'), models.Index(fields=['is_active'], name='recipes_cui_is_acti_0ef43e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='recipes_ing_slug_9dd33f_idx'), models.Index(fields=['is_active'], name='recipes_ing_is_acti_cd8dd6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('summary', models.TextField(verbose_name='Summary')),
                ('instructions', models.TextField(verbose_name='Instructions')),
                ('preparation_time', models.PositiveSmallIntegerField(verbose_name='Preparation Time')),
                ('cooking_time', models.PositiveSmallIntegerField(verbose_name='Cooking Time')),
                ('servings', models.PositiveSmallIntegerField(default=1, verbose_name='Servings')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20, verbose_name='Difficulty')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('favorite_count', models.PositiveIntegerField(default=0, verbose_name='Favorite Count')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, max_length=320, verbose_name='Meta Description')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('source_url', models.URLField(blank=True, verbose_name='Source URL')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='recipes.category')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='provinces.province')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='recipes/', verbose_name='Image')),
                ('alt_text', models.CharField(max_length=255, verbose_name='Alt Text')),
                ('is_cover', models.BooleanField(db_index=True, default=False, verbose_name='Cover Image')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Sort Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Recipe Image',
                'verbose_name_plural': 'Recipe Images',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Quantity')),
                ('unit', models.CharField(choices=[('g', 'Gram'), ('kg', 'Kilogram'), ('ml', 'Milliliter'), ('l', 'Liter'), ('tsp', 'Tea Spoon'), ('tbsp', 'Table Spoon'), ('cup', 'Cup'), ('piece', 'Piece'), ('pinch', 'Pinch'), ('optional', 'Optional')], default='g', max_length=10, verbose_name='Unit')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Sort Order')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='recipes.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Recipe Ingredient',
                'verbose_name_plural': 'Recipe Ingredients',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='recipes_tag_slug_3ea026_idx'), models.Index(fields=['is_active'], name='recipes_tag_is_acti_feb833_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecipeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='recipes.recipe')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='recipes.tag')),
            ],
            options={
                'verbose_name': 'Recipe Tag',
                'verbose_name_plural': 'Recipe Tags',
                'ordering': ('tag__name',),
            },
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['slug'], name='recipes_rec_slug_412256_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['status'], name='recipes_rec_status_d54da6_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['is_active'], name='recipes_rec_is_acti_de97fe_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['is_featured'], name='recipes_rec_is_feat_75f06e_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['province'], name='recipes_rec_provinc_cfdfd8_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['category'], name='recipes_rec_categor_4c01e4_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['published_at'], name='recipes_rec_publish_bf46c2_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['created_at'], name='recipes_rec_created_a55f59_idx'),
        ),
        migrations.AddIndex(
            model_name='recipeimage',
            index=models.Index(fields=['recipe'], name='recipes_rec_recipe__8b8a5e_idx'),
        ),
        migrations.AddIndex(
            model_name='recipeimage',
            index=models.Index(fields=['is_cover'], name='recipes_rec_is_cove_5d7eaa_idx'),
        ),
        migrations.AddIndex(
            model_name='recipeimage',
            index=models.Index(fields=['sort_order'], name='recipes_rec_sort_or_0f8755_idx'),
        ),
        migrations.AddConstraint(
            model_name='recipeimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('recipe',), name='unique_cover_image_per_recipe'),
        ),
        migrations.AddIndex(
            model_name='recipeingredient',
            index=models.Index(fields=['recipe'], name='recipes_rec_recipe__6c6558_idx'),
        ),
        migrations.AddIndex(
            model_name='recipeingredient',
            index=models.Index(fields=['ingredient'], name='recipes_rec_ingredi_65e62b_idx'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_recipe_ingredient'),
        ),
        migrations.AddIndex(
            model_name='recipetag',
            index=models.Index(fields=['recipe'], name='recipes_rec_recipe__301a75_idx'),
        ),
        migrations.AddIndex(
            model_name='recipetag',
            index=models.Index(fields=['tag'], name='recipes_rec_tag_id_bb695a_idx'),
        ),
        migrations.AddConstraint(
            model_name='recipetag',
            constraint=models.UniqueConstraint(fields=('recipe', 'tag'), name='unique_recipe_tag'),
        ),
    ]
