# Generated by Django 6.0.6 on 2026-07-16 19:12

import recipes.validators.image_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_options_alter_recipetag_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(upload_to='recipes/', validators=[recipes.validators.image_validator.ImageValidator.validate_image], verbose_name='Image'),
        ),
    ]
